### PR TITLE
Maemo/ascii devel

### PR DESCRIPTION
**Pull request by spinal84**
- Update debian compat level to 10
- Migrate to dh build sequencer
- Add multiarch support
- Fix warnings

### CODE REVIEW

**Comment by freemangordon** [comment]
looks good to me

**Comment by parazyd** [comment]
Looks good. @MerlijnWajer ?

**Comment by MerlijnWajer** [comment]
Looks fine.

**Comment by spinal84** [comment]
Should I accept it myself?

**Comment by MerlijnWajer** [comment]
In the future - yeah sure, why not. Merged!

**Pull request merged**
